# Generated by Django 5.2.4 on 2025-07-29 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompletedTenderCustomers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'completed_tender_customers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CompletedTenderList',
            fields=[
                ('completed_tender_id', models.AutoField(primary_key=True, serialize=False)),
                ('tender_name', models.CharField(max_length=255)),
                ('tender_received_date', models.DateField()),
                ('tender_due_date', models.DateField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('added_by', models.CharField(blank=True, max_length=255, null=True)),
                ('estimator', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('email_id', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'completed_tender_list',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('bill_to', models.CharField(blank=True, max_length=255, null=True)),
                ('fname', models.CharField(blank=True, max_length=100, null=True)),
                ('lname', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('mob', models.CharField(blank=True, max_length=50, null=True)),
                ('street1', models.CharField(blank=True, max_length=255, null=True)),
                ('street2', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('postcode', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('on_stop', models.BooleanField(default=False)),
                ('is_unverified', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'customers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TenderList',
            fields=[
                ('tender_id', models.AutoField(primary_key=True, serialize=False)),
                ('tender_name', models.CharField(max_length=255)),
                ('tender_received_date', models.DateField()),
                ('tender_due_date', models.DateField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('is_not_quoting', models.BooleanField(default=False)),
                ('is_completed', models.BooleanField(default=False)),
                ('quote_created', models.BooleanField(default=False)),
                ('added_by', models.CharField(blank=True, max_length=255, null=True)),
                ('estimator', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('email_id', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'tender_list',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TenderListCustomers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'tender_list_customers',
                'managed': False,
            },
        ),
    ]
