# Generated by Django 5.2.4 on 2025-08-01 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Estimating', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotQuotingCustomers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'not_quoting_customers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NotQuotingList',
            fields=[
                ('not_quoting_id', models.AutoField(primary_key=True, serialize=False)),
                ('tender_name', models.CharField(max_length=255)),
                ('tender_received_date', models.DateField()),
                ('tender_due_date', models.DateField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('added_by', models.CharField(blank=True, max_length=255, null=True)),
                ('estimator', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('email_id', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'not_quoting_list',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EstimatorAcronym',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, unique=True)),
                ('short_code', models.CharField(max_length=10)),
            ],
        ),
    ]
